### ISSUE TITLE
[Feature request] Improve notification (dark notification & options)

### ISSUE THREAD

**Issue by Drhaal** [enricocid/Music-Player-GO#168]
On android 9 the playing notification is white even when the app is set on dark theme.

**Comment by enricocid** [comment]
Hello & thanks for the FR.
Have You tried to enable automatic theme? (I'm unfortunately on Android 10 now so can't test for myself).

At the moment it is not possible to make the notification dark as I'm using the Media style which gives me a better control on the actions and how the notification looks when expanded/collapsed.

I will add it later as it will require to implement a custom view, Consider I'm actually not working on new implementations but I'm in maintanance mode only. Because of the weird situation here in Italy I've decided to get a break from development as I'm experiencing a lack of motivation... I hope You will understand. Thanks.

**Comment by Johnett** [comment]
> 
> 
> At the moment it is not possible to make the notification dark as I'm using the Android media style which gives me better control over the actions and how the notification looks when expanded/collapsed.
> 
You are absolutely right.





> 
> Because of the weird situation here in Italy, I've decided to get a break from development as I'm experiencing a lack of motivation... I hope You will understand. Thanks.

Take care. My prayers are with you.

**Comment by Drhaal** [comment]
I tried to enable the automatic theme but it stays on white even with a dark system theme. Might be a problem with LOS.

> Because of the weird situation here in Italy, I've decided to get a break from development as I'm experiencing a lack of motivation... I hope You will understand. Thanks.

Of course i understand situation is kinda weird here in france too. Hope you will get your motivation back^^. 
 And thanks for the app it's realy nice.

**Comment by enricocid** [comment]
> I tried to enable the automatic theme but it stays on white even with a dark system theme. Might be a problem with LOS.

I'm not sure there's a problem with LOS. Too bad I've updated to Android 10 on my Mi A2 Lite ... Now I can't flash any ROM as there's no Android 10 fastboot image available (can't rollback).
Don't worry, as soon as I will be able to flash LOS or a Pie ROM I will be able to test.

Anyway, the feature will be added for sure. I will probably add an option to let the users enable custom notifications ;)

> Of course i understand situation is kinda weird here in france too. Hope you will get your motivation back^^.
> And thanks for the app it's realy nice.

Thanks for the feedback :)

**Comment by enricocid** [comment]
Hi,

I resolved the issue with notification by setting a dark default album art

Notifications do not follow day/night theme and I don't want to implement a custom layout to take advantage of the native media player s notification.

I think this is the best solution for devices supporting colorized notifications.

Hope You like it 

![image](https://user-images.githubusercontent.com/7274841/98369549-6d113100-2039-11eb-801e-574fb6c5961d.png)
