### ISSUE TITLE
oled dark mode

### ISSUE THREAD

**Issue by nonetrix** [enricocid/Music-Player-GO#174]

**Comment by enricocid** [comment]
Could You elaborate please?

**Comment by nonetrix** [comment]
> Could You elaborate please? :)

dark mode but completely black to save battery life on oled screens

**Comment by enricocid** [comment]
Thanks, but as suggested in the [docs](https://material.io/design/color/dark-theme.html#usage) we should use dark grey rather than deep black.
The difference in power savings of black dark modes as compared to dark gray modes is so small that it's negligible.
I'm gonna leave this issue open. Once I will be able to work on MPGO again I'm gonna try to implement deep black mode and see what happens :)

**Comment by enricocid** [comment]
Closing. As explained in the faq (Where is the deep black dark theme?) and the official docs, it is highly recommended to "darken with grey rather than black"
