### ISSUE TITLE
Storage Permission

### ISSUE THREAD

**Issue by jZ9tZs** [enricocid/Music-Player-GO#195]
Storage permissions should be removed for apps targeting API 29+ unless they opt into legacy storage; and API 30+ removes that opt-in. So the storage permission would be removed when moving to the current API level. Opting into legacy storage for API level 29 is a security issue because apps have their internal storage directory without any permissions. 
https://developer.android.com/training/data-storage#permissions

**Comment by enricocid** [comment]
This is true only if you rely on the app's private folder or you try to access the media files created by the app (vectorify da home for example saves images to the scoped storage and does not require any permission).

To access media files outside the app's scoped storage you need to request read storage permission or the MediaStore query will fail.

This issue was raised months ago by other users and I did the necessary changes.

"Opting into legacy storage for API level 29 is a security issue because..."

The app does not opt in for legacy storage. That's not true.

To play media files and to get birtrate MPGO actually relies on content uri. This applies to all Android versions supported.

Raw path is not even being accessed in Android 10 and above.
To get folders MPGO actually queries the new MediaStore's AudioColumns.BUCKET_DISPLAY_NAME column which is available from Android 10 and above.

Raw paths are accessed only on Android versions below Android 10 to organize the folders fragment. Raw path are not persisted into preferences as suggested in the docs.

So I think the app is compliant or it would throw security exceptions as in the past.

**Comment by jZ9tZs** [comment]
You are right, I didn't read carefully enough. Thank you for the explanation.

**Comment by jZ9tZs** [comment]
> To access media files outside the app's scoped storage you need to request read storage permission or the MediaStore query will fail.

But wouldn't it be possible to use SAF to access files and directories by asking the user to pick them?
https://developer.android.com/training/data-storage/shared/documents-files

**Comment by enricocid** [comment]
> > To access media files outside the app's scoped storage you need to request read storage permission or the MediaStore query will fail.
> 
> But wouldn't it be possible to use SAF to access files and directories by asking the user to pick them?
> https://developer.android.com/training/data-storage/shared/documents-files

I think is simpler using runtime permissions. 
I already had to deal with SAF in the past and I remember it was such a mess.
You need to instruct the user on how to grant permissions adding many lines of code for dialogs, intro etc.
Runtime permission is simpler

**Comment by nic0lette** [comment]
> > To access media files outside the app's scoped storage you need to request read storage permission or the MediaStore query will fail.
> 
> But wouldn't it be possible to use SAF to access files and directories by asking the user to pick them?
> https://developer.android.com/training/data-storage/shared/documents-files

You could use SAF to gain access to music files, but SAF is really best suited for accessing "documents" rather than media. For this app, I'd definitely recommend sticking with media store and requesting READ_EXTERNAL_STORAGE.

requestLegacyStorage is only required on Android 10 if the app accesses media via file paths (by reading the `DATA` column in Media Store). If that's needed, then yes, opting out is the right way to proceed, and file access continues to be available in Android 11 (for media files).

**Comment by enricocid** [comment]
Closing, gonna stick to runtime permission.😉
