### ISSUE TITLE
support for equalizer

### ISSUE THREAD

**Issue by sethtara** [enricocid/Music-Player-GO#214]
This is an issue regarding the issue with equalizer

while tapping on equalizer option says : "No equalizer found"

having a equalizer will be amazing

**Comment by enricocid** [comment]
Is Your phone running Android 10?
Unfortunately there's no eq in Android 10.

Since there's already an issue #66 I'm gonna close this.

Equalizer is in my todo list and I'm gonna add it for sure in the next release. Unfortunately I can't work on this in this particular period as I'm experiencing some issues.

**Comment by enricocid** [comment]
Built in Equalizer added 😉

https://github.com/enricocid/Music-Player-GO/issues/66#issuecomment-723619970

It will be available in the next update 👍🏻
