### ISSUE TITLE
Repeating option automatically disable after the end of currently playing song

### ISSUE THREAD

**Issue by rockstar96969696** [enricocid/Music-Player-GO#23]
Repeating option does not work correctly

**Comment by enricocid** [comment]
That's the normal behaviour. Personally I don't want to listen the same song repeatedly but only one time

**Comment by rockstar96969696** [comment]
Are you the developer?

**Comment by enricocid** [comment]
Yes

**Comment by rockstar96969696** [comment]
This music player is for public not especially for you...

**Comment by rockstar96969696** [comment]
If you insert the repeating option then it must done its job without any bug

**Comment by rockstar96969696** [comment]
I help you to find the bugs and help to improve your hard work by my ideas.

**Comment by enricocid** [comment]
Hmmm, not exactly. 

1. If you don't like a feature it doesn't mean it is a bug, just move to another player.
The repeating option works as expected: the song is played one more time and then disabled.

2. The app is exactly what I need. It reflects my needs and its development will always be strictly driven by them. I'm open to suggestions (and I have already merged some of them) but ultimately the choice is mine

3. I'm an open source fan, and I always share the code/app as it can help others.

Closing the issue because it is not a real big/issue
