### ISSUE TITLE
[BUG] Notification not posted

### ISSUE THREAD

**Issue by chenjie199234** [enricocid/Music-Player-GO#404]
1) **Describe the bug**
didn't show music info in the drop down menu

2) **To Reproduce the behaviour**
![gif-20220419-093924](https://user-images.githubusercontent.com/29348971/163906151-dbbbb721-cb7f-4f4f-9cd2-268d6646e6e9.gif)

3) **Expected behavior**
drop down menu has music info

5) **Smartphone (please complete the following information):**
 - Device: Motorola edge s30
 - OS: Android 12
 - ROM or mods: MyUI 3.0 (Motorola's system)

**Comment by enricocid** [comment]
Hi, thanks.
Could you try to reproduce the bug with another player like phonograph or shuttle or [audio](https://github.com/OxygenCobalt/Auxio)? Thanks :)

**Comment by chenjie199234** [comment]
@enricocid confirm,works on auxio

**Comment by OxygenCobalt** [comment]
@enricocid I'd consider three possibilities:

1. OP might be stopping playback every time they exit the app, by accident. @chenjie199234 Are you sure you are pressing the 
"No" option every time you exit?
2. Some OEM skins like to use the `MediaSession` to get playback information, not the notification.  I tried my best to resolve this insanity with my [`PlaybackSessionConnector`](https://github.com/OxygenCobalt/Auxio/blob/dev/app/src/main/java/org/oxycblt/auxio/playback/system/PlaybackSessionConnector.kt) class. However, looking at your project, you effectively do the same thing, just fragmented all over and with MediaPlayer instead of ExoPlayer. It might be a logic bug regarding how you handle that.
3. If the phone using the `Notification`, then perhaps it's a logic bug that prevents the notification from being posted?
4. Perhaps there is some flag set with the service/`MediaSession`/notification that Motorola skins need to determine if the notification is for music or not. This is weird, but possible.

**Comment by enricocid** [comment]
Thanks @OxygenCobalt. 😊🙏🏻
What about priority? I'm using PRIORITY_LOW.

**Comment by OxygenCobalt** [comment]
@enricocid I don't set the priority, I just keep it at the default priority.

**Comment by enricocid** [comment]
@chenjie199234 
Could you try this?
:)
https://drive.google.com/file/d/1e-BHeAMUus8Kd5IEzcpPkHLD5A4yQ8Xr/view?usp=sharing

**Comment by enricocid** [comment]
Hi @chenjie199234 

Test apk 1
https://drive.google.com/file/d/1e-BHeAMUus8Kd5IEzcpPkHLD5A4yQ8Xr/view?usp=sharing

Test apk 2
https://drive.google.com/file/d/1VSH1Q-gkqQIvcl9MFOKyx0K2a8fJXpDJ/view?usp=sharing

**Comment by chenjie199234** [comment]
@enricocid both test 1 and test 2 can show music info in drop down menu.
but click next and prev will replay the current music

**Comment by enricocid** [comment]
Thanks. How many songs there are in the album?
If one, then it is normal. Skip songs between albums still not supported. 😉

**Comment by chenjie199234** [comment]
@enricocid
only one song in the album.
so the next and prev button only work in album,not the play list?

**Comment by enricocid** [comment]
Skip button works in single albums and queue 😊
I will add possibility to skip between albums and artists in next updates 👍🏻
