### ISSUE TITLE
Question: Does it play HD Audio without downgrading?

### ISSUE THREAD

**Issue by lamyergeier** [enricocid/Music-Player-GO#413]
I am using Android 11 with Samsung One UI 3.1

I want to play Audio frequency 192 kHz, 24 bit depth flac files. The app plays it successfully, but does it or android downgrades the quality while processing to standard CD quality 44.1 kHz and 16 bit depth? 

Or, is the output truly HD Audio?

**Comment by enricocid** [comment]
Hi, the app does make use of native Media player.
For details please have a look at this page:
https://developer.android.com/guide/topics/media/media-formats

**Comment by OxygenCobalt** [comment]
As far as I know, the android media player tends to downsample any audio to 16-bit depth. You can use ExoPlayer in an app to work around this and output audio at higher bitrates, but this is highly experimental and disables a lot of features.

**Comment by lamyergeier** [comment]
> As far as I know, the android media player tends to downsample any audio to 16-bit depth. You can use ExoPlayer in an app to work around this and output audio at higher bitrates, but this is highly experimental and disables a lot of features.

@OxygenCobalt Does Auxio which uses Exo Player support high resolution playback? Is there any way to enable this as I don't see this in the settings. Secondly, I read about the drawbacks of exoplayer, and since I am running Android 11, I don't need to be concerned of the battery draining issue. What features gets disabled? Could you please specify a bit?

**Comment by OxygenCobalt** [comment]
@lamyergeier I don't sadly. HD playback with ExoPlayr seems to have the following drawbacks:
- It only works on the newer versions of Android that support higher bitrates, which doesn't matter for you but probably matters for other people who want HD audio on older devices.
- I can't modify the audio bitstream at all. This more or less disables ReplayGain functionality, which feels like an annoying trade-off.
- ExoPlayer seems to be much less efficient with HD audio on, which is why I said it was highly experimental.

It seems like something interesting to add, but for me it seems like it would take some time to figure out how limited I truly am with ExoPlayer until I try to implement it.

**Comment by lamyergeier** [comment]
@OxygenCobalt People who are interested in HD Audio would most likely not want Replay Gain as the very fact they are listening to HD audio is to experience wider dynamic range and would prefer the audio to be unmodified as possible.

May be android supports different app version for different android version. So you could offfer HD audio feature in modern Android operating systems.

**Comment by OxygenCobalt** [comment]
@Iamyergeier That's interesting. This discussion is out of scope now, but I'll look further into it in the future.

**Comment by lamyergeier** [comment]
@enricocid so the app can play HD audio without loss?
