### ISSUE TITLE
[BUG] Equalizer not available on device without system equalizer

### ISSUE THREAD

**Issue by robsiera** [enricocid/Music-Player-GO#424]
1) **Describe the bug**
Under Settings > Audio > Equalizer, there is the following note:
`Note: The system equalizer is used unless turned off from the system settings. :)`
However, on a [e.foundation](https://e.foundation/e-os/) de-googled Samsung 9 phone, among others, there is not system equalizer.
Isn't it possible in such a case to make the build in equalizer available?

**Comment by enricocid** [comment]
Android version?

______________________

You can try to search for audiofx or any other equalizer in settings>app (show system) and disable it. 

Android relies on global EQ which controls all volumes and settings for all apps playing sound natively. 
The inbuilt EQ is just a link to the system Equalizer (https://developer.android.com/reference/android/media/audiofx/Equalizer).
If the Android system is missing (as found in some Samsung, HTC, Pixel, etc.) the EQ control then there is nothing for MPGO to link to.

I'm pretty sure Samsung does originally add a custom equalizer to their devices. 
This equalizer relies on an internal audio engine rather than the native one. So it has a dedicated set of libs/kernel mods that would clash with the native equalizer.
So it is not added to the product during the build process.

That's something you should ask to the ROM maintainers.

Alternatively, you can use an equalizer that relies on internal audio engine and interacts with the media session, like wavelet, or the stock one (if you are able to retrieve it). That's the only solution 😁

**Comment by robsiera** [comment]
ok, then the bug is the inaccurate note?
Maybe in this case you could say something like this?
`Note: No system equalizer found. We need that for our implementation. :(`

**Comment by enricocid** [comment]
Try this apk @robsiera 

https://drive.google.com/file/d/1OKPEybKW-jC5COlW9fswJ6S4Blr6zheh/view?usp=sharing

**Comment by enricocid** [comment]
try this apk @robsiera 

https://drive.google.com/file/d/1gVN7uGxfyu86DfME1UeHKCUE2QzCJ9oK/view?usp=sharing
