### ISSUE TITLE
[FR]: Music Player Go not selectable as audio app in Gadgetbridge

### ISSUE THREAD

**Issue by anmith** [enricocid/Music-Player-GO#494]
### What feature would you like to see?

In Gadgetbridge (open source app for connection to watches etc) there's an option to select a music player to be used by Gadgetbridge to be controlled by the connected gadget. It would be cool to be able to remove control Music Player Go, too.

### What kind of level is this feature request?

Hmm, probably intermediate, can't know!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OxygenCobalt** [comment]
@enricocid I've encountered this issue before. Basically, Gadgetbridge is stuck in 2011 and blindly queries a broadcast receiver that can handle the `ACTION_MEDIA_BUTTON` intent to find music apps, instead of querying for active media sessions. You have to register a `MediaButtonReciever` (I think it's called something like that) within your manifest and then handle it in your service for it to work.

**Comment by enricocid** [comment]
@anmith try this one: https://drive.google.com/file/d/1jvDubrmHlMxO_yjPV_Az6FQlXVUyEBXP/view?usp=share_link

@OxygenCobalt Thanks ;)

**Comment by anmith** [comment]
@enricocid 
Sorry for the delayed feedback. I received the new version via F-Droid this week and Music Player Go is selected as preferred audio player. Thanks a lot!
