### ISSUE TITLE
handle duplicate files

### ISSUE THREAD

**Issue by travisfw** [enricocid/Music-Player-GO#74]
A couple albums are saved in two places on my phone. Selecting those albums shows lists of songs where each song is listed twice. I'm not interested in deleting one of them, and I don't think a music player should be opinionated about the number of copies of music on a phone.

Would it make sense to deduplicate these lists, in the case that two consecutive song names are exactly the same and the two files have exactly the same checksum?

**Comment by enricocid** [comment]
I'm already aware of the issue. The problem is the query I'm using to retrieve the audio files.
When a new audio file is found, a new [Music](https://github.com/enricocid/Music-Player-GO/blob/master/project/app/src/main/java/com/iven/musicplayergo/music/Music.kt) is created, which contains also the path beside title, album, artist etc, which is different.
That's why it is listed twice. Need to find something unique in the MediaStore.
